INSERT INTO Clientes (Nome, Email, Telefone) VALUES (N'Ana Carolina Souza', N'ana.souza@exemplo.com', N'(11)98800-0001');
INSERT INTO Clientes (Nome, Email, Telefone) VALUES (N'João Pedro Almeida', N'joao.almeida@exemplo.com', N'(11)98800-0002');
INSERT INTO Clientes (Nome, Email, Telefone) VALUES (N'Maria Eduarda Lima', N'maria.lima@exemplo.com', N'(11)98800-0003');
INSERT INTO Clientes (Nome, Email, Telefone) VALUES (N'Bruno Henrique Ferreira', N'bruno.ferreira@exemplo.com', N'(11)98800-0004');
INSERT INTO Clientes (Nome, Email, Telefone) VALUES (N'Larissa Oliveira', N'larissa.oliveira@exemplo.com', N'(11)98800-0005');
INSERT INTO Clientes (Nome, Email, Telefone) VALUES (N'Rafael Gomes', N'rafael.gomes@exemplo.com', N'(11)98800-0006');
INSERT INTO Clientes (Nome, Email, Telefone) VALUES (N'Juliana Martins', N'juliana.martins@exemplo.com', N'(11)98800-0007');
INSERT INTO Clientes (Nome, Email, Telefone) VALUES (N'Lucas Silva', N'lucas.silva@exemplo.com', N'(11)98800-0008');
INSERT INTO Clientes (Nome, Email, Telefone) VALUES (N'Amanda Rocha', N'amanda.rocha@exemplo.com', N'(11)98800-0009');
INSERT INTO Clientes (Nome, Email, Telefone) VALUES (N'Felipe Duarte', N'felipe.duarte@exemplo.com', N'(11)98800-0010');
INSERT INTO Clientes (Nome, Email, Telefone) VALUES (N'Camila Pires', N'camila.pires@exemplo.com', N'(11)98800-0011');
INSERT INTO Clientes (Nome, Email, Telefone) VALUES (N'Gustavo Azevedo', N'gustavo.azevedo@exemplo.com', N'(11)98800-0012');
INSERT INTO Clientes (Nome, Email, Telefone) VALUES (N'Beatriz Ramos', N'beatriz.ramos@exemplo.com', N'(11)98800-0013');
INSERT INTO Clientes (Nome, Email, Telefone) VALUES (N'Daniel Costa', N'daniel.costa@exemplo.com', N'(11)98800-0014');
INSERT INTO Clientes (Nome, Email, Telefone) VALUES (N'Letícia Cardoso', N'leticia.cardoso@exemplo.com', N'(11)98800-0015');
INSERT INTO Clientes (Nome, Email, Telefone) VALUES (N'Vinícius Moraes', N'vinicius.moraes@exemplo.com', N'(11)98800-0016');
INSERT INTO Clientes (Nome, Email, Telefone) VALUES (N'Gabriela Mendes', N'gabriela.mendes@exemplo.com', N'(11)98800-0017');
INSERT INTO Clientes (Nome, Email, Telefone) VALUES (N'Diego Santana', N'diego.santana@exemplo.com', N'(11)98800-0018');
INSERT INTO Clientes (Nome, Email, Telefone) VALUES (N'Natália Barbosa', N'natalia.barbosa@exemplo.com', N'(11)98800-0019');
INSERT INTO Clientes (Nome, Email, Telefone) VALUES (N'Leonardo Cunha', N'leonardo.cunha@exemplo.com', N'(11)98800-0020');
INSERT INTO Clientes (Nome, Email, Telefone) VALUES (N'Patrícia Ribeiro', N'patricia.ribeiro@exemplo.com', N'(11)98800-0021');
INSERT INTO Clientes (Nome, Email, Telefone) VALUES (N'André Nogueira', N'andre.nogueira@exemplo.com', N'(11)98800-0022');
INSERT INTO Clientes (Nome, Email, Telefone) VALUES (N'Mariana Teixeira', N'mariana.teixeira@exemplo.com', N'(11)98800-0023');
INSERT INTO Clientes (Nome, Email, Telefone) VALUES (N'Rodrigo Antunes', N'rodrigo.antunes@exemplo.com', N'(11)98800-0024');
INSERT INTO Clientes (Nome, Email, Telefone) VALUES (N'Bianca Monteiro', N'bianca.monteiro@exemplo.com', N'(11)98800-0025');
INSERT INTO Clientes (Nome, Email, Telefone) VALUES (N'Henrique Passos', N'henrique.passos@exemplo.com', N'(11)98800-0026');
INSERT INTO Clientes (Nome, Email, Telefone) VALUES (N'Tamires Dias', N'tamires.dias@exemplo.com', N'(11)98800-0027');
INSERT INTO Clientes (Nome, Email, Telefone) VALUES (N'Caio Rezende', N'caio.rezende@exemplo.com', N'(11)98800-0028');
INSERT INTO Clientes (Nome, Email, Telefone) VALUES (N'Elaine Farias', N'elaine.farias@exemplo.com', N'(11)98800-0029');
INSERT INTO Clientes (Nome, Email, Telefone) VALUES (N'Eduardo Tavares', N'eduardo.tavares@exemplo.com', N'(11)98800-0030');

INSERT INTO Tecnicos (Nome, Especialidade) VALUES (N'João Azevedo', N'Geral');
INSERT INTO Tecnicos (Nome, Especialidade) VALUES (N'Marcelo Tardin', N'Geral');
INSERT INTO Tecnicos (Nome, Especialidade) VALUES (N'Marcia Souza', N'Hidráulica');
INSERT INTO Tecnicos (Nome, Especialidade) VALUES (N'Rodrigo Oliveira', N'Elétrica');
INSERT INTO Tecnicos (Nome, Especialidade) VALUES (N'Ruana Macedo', N'Hidráulica');

INSERT INTO Produtos (Nome, Descricao) VALUES (N'Consulta de Marketing Digital', N'Sessão individual com análise de redes sociais e estratégias de conteúdo.');
INSERT INTO Produtos (Nome, Descricao) VALUES (N'Desenvolvimento de Site Pessoal', N'Criação de site com até 3 páginas, layout responsivo e formulário de contato.');
INSERT INTO Produtos (Nome, Descricao) VALUES (N'Manutenção de Computadores', N'Serviço completo de limpeza, formatação e otimização de sistema.');
INSERT INTO Produtos (Nome, Descricao) VALUES (N'Consultoria Financeira Pessoal', N'Acompanhamento para organização de finanças e planejamento de metas.');
INSERT INTO Produtos (Nome, Descricao) VALUES (N'Aula Particular de Inglês Online', N'Aula individual com foco em conversação, via videoconferência.');
INSERT INTO Produtos (Nome, Descricao) VALUES (N'Consultoria em Branding Pessoal', N'Desenvolvimento de identidade visual e posicionamento para profissionais autônomos.');
INSERT INTO Produtos (Nome, Descricao) VALUES (N'Consultoria para Lançamento de Produto', N'Planejamento estratégico de mercado, precificação e validação de ideias.');
INSERT INTO Produtos (Nome, Descricao) VALUES (N'Consultoria em UX/UI Design', N'Análise de experiência do usuário e melhorias na interface de sites e aplicativos.');
INSERT INTO Produtos (Nome, Descricao) VALUES (N'Consultoria para E-commerce', N'Orientação sobre plataformas, logística, meios de pagamento e estratégias de venda online.');
INSERT INTO Produtos (Nome, Descricao) VALUES (N'Consultoria em Produtividade e Rotina', N'Auxílio na organização do tempo, definição de metas e construção de hábitos eficientes.');

INSERT INTO Ordens (ClienteID, TecnicoID, DataAbertura, DataConclusao, Status) VALUES (7, 4, N'2024-02-08', N'2024-02-14', N'Concluída');
INSERT INTO Ordens (ClienteID, TecnicoID, DataAbertura, DataConclusao, Status) VALUES (5, 1, N'2024-02-26', N'2024-02-28', N'Concluída');
INSERT INTO Ordens (ClienteID, TecnicoID, DataAbertura, DataConclusao, Status) VALUES (5, 4, N'2024-01-13', N'2024-01-15', N'Concluída');
INSERT INTO Ordens (ClienteID, TecnicoID, DataAbertura, DataConclusao, Status) VALUES (10, 4, N'2024-01-16', N'2024-01-26', N'Concluída');
INSERT INTO Ordens (ClienteID, TecnicoID, DataAbertura, DataConclusao, Status) VALUES (2, 5, N'2024-02-02', N'2024-02-08', N'Concluída');
INSERT INTO Ordens (ClienteID, TecnicoID, DataAbertura, DataConclusao, Status) VALUES (3, 4, N'2024-01-16', N'2024-01-22', N'Concluída');
INSERT INTO Ordens (ClienteID, TecnicoID, DataAbertura, DataConclusao, Status) VALUES (7, 3, N'2024-01-20', N'2024-01-23', N'Concluída');
INSERT INTO Ordens (ClienteID, TecnicoID, DataAbertura, DataConclusao, Status) VALUES (10, 2, N'2024-02-11', N'2024-02-21', N'Concluída');
INSERT INTO Ordens (ClienteID, TecnicoID, DataAbertura, DataConclusao, Status) VALUES (7, 5, N'2024-03-01', N'2024-03-06', N'Concluída');
INSERT INTO Ordens (ClienteID, TecnicoID, DataAbertura, DataConclusao, Status) VALUES (10, 2, N'2024-02-22', N'2024-03-03', N'Concluída');
INSERT INTO Ordens (ClienteID, TecnicoID, DataAbertura, DataConclusao, Status) VALUES (9, 4, N'2024-01-30', N'2024-02-02', N'Concluída');
INSERT INTO Ordens (ClienteID, TecnicoID, DataAbertura, DataConclusao, Status) VALUES (4, 2, N'2024-01-16', N'2024-01-23', N'Concluída');
INSERT INTO Ordens (ClienteID, TecnicoID, DataAbertura, DataConclusao, Status) VALUES (3, 4, N'2024-02-20', N'2024-02-29', N'Concluída');
INSERT INTO Ordens (ClienteID, TecnicoID, DataAbertura, DataConclusao, Status) VALUES (8, 2, N'2024-02-02', N'2024-02-12', N'Concluída');
INSERT INTO Ordens (ClienteID, TecnicoID, DataAbertura, DataConclusao, Status) VALUES (7, 3, N'2024-01-08', N'2024-01-12', N'Concluída');
INSERT INTO Ordens (ClienteID, TecnicoID, DataAbertura, DataConclusao, Status) VALUES (6, 2, N'2024-01-31', N'2024-02-01', N'Concluída');
INSERT INTO Ordens (ClienteID, TecnicoID, DataAbertura, DataConclusao, Status) VALUES (5, 5, N'2024-01-15', N'2024-01-17', N'Concluída');
INSERT INTO Ordens (ClienteID, TecnicoID, DataAbertura, DataConclusao, Status) VALUES (5, 2, N'2024-02-07', N'2024-02-11', N'Concluída');
INSERT INTO Ordens (ClienteID, TecnicoID, DataAbertura, DataConclusao, Status) VALUES (9, 2, N'2024-01-17', N'2024-01-21', N'Concluída');
INSERT INTO Ordens (ClienteID, TecnicoID, DataAbertura, DataConclusao, Status) VALUES (5, 2, N'2024-01-12', N'2024-01-22', N'Concluída');
INSERT INTO Ordens (ClienteID, TecnicoID, DataAbertura, DataConclusao, Status) VALUES (11, 3, N'2024-03-10', NULL, N'Em andamento');
INSERT INTO Ordens (ClienteID, TecnicoID, DataAbertura, DataConclusao, Status) VALUES (12, 1, N'2024-03-12', NULL, N'Em andamento');
INSERT INTO Ordens (ClienteID, TecnicoID, DataAbertura, DataConclusao, Status) VALUES (13, 5, N'2024-03-01', NULL, N'Pendente');
INSERT INTO Ordens (ClienteID, TecnicoID, DataAbertura, DataConclusao, Status) VALUES (14, 2, N'2024-02-18', N'2024-02-20', N'Cancelada');
INSERT INTO Ordens (ClienteID, TecnicoID, DataAbertura, DataConclusao, Status) VALUES (15, 4, N'2024-04-01', NULL, N'Agendada');
INSERT INTO Ordens (ClienteID, TecnicoID, DataAbertura, DataConclusao, Status) VALUES (16, 1, N'2024-03-20', NULL, N'Em andamento');
INSERT INTO Ordens (ClienteID, TecnicoID, DataAbertura, DataConclusao, Status) VALUES (17, 2, N'2024-02-27', NULL, N'Pendente');
INSERT INTO Ordens (ClienteID, TecnicoID, DataAbertura, DataConclusao, Status) VALUES (18, 3, N'2024-03-08', NULL, N'Em andamento');
INSERT INTO Ordens (ClienteID, TecnicoID, DataAbertura, DataConclusao, Status) VALUES (19, 4, N'2024-04-03', NULL, N'Agendada');
INSERT INTO Ordens (ClienteID, TecnicoID, DataAbertura, DataConclusao, Status) VALUES (20, 5, N'2024-03-15', N'2024-03-17', N'Cancelada');
INSERT INTO Ordens (ClienteID, TecnicoID, DataAbertura, DataConclusao, Status) VALUES (21, 1, N'2024-03-10', NULL, N'Em andamento');
INSERT INTO Ordens (ClienteID, TecnicoID, DataAbertura, DataConclusao, Status) VALUES (22, 2, N'2024-03-11', NULL, N'Pendente');
INSERT INTO Ordens (ClienteID, TecnicoID, DataAbertura, DataConclusao, Status) VALUES (23, 3, N'2024-03-22', NULL, N'Agendada');
INSERT INTO Ordens (ClienteID, TecnicoID, DataAbertura, DataConclusao, Status) VALUES (24, 4, N'2024-03-05', N'2024-03-09', N'Cancelada');
INSERT INTO Ordens (ClienteID, TecnicoID, DataAbertura, DataConclusao, Status) VALUES (25, 5, N'2024-03-30', NULL, N'Em andamento');
INSERT INTO Ordens (ClienteID, TecnicoID, DataAbertura, DataConclusao, Status) VALUES (26, 1, N'2024-03-01', NULL, N'Pendente');
INSERT INTO Ordens (ClienteID, TecnicoID, DataAbertura, DataConclusao, Status) VALUES (27, 2, N'2024-03-12', NULL, N'Agendada');
INSERT INTO Ordens (ClienteID, TecnicoID, DataAbertura, DataConclusao, Status) VALUES (28, 3, N'2024-03-08', NULL, N'Em andamento');
INSERT INTO Ordens (ClienteID, TecnicoID, DataAbertura, DataConclusao, Status) VALUES (29, 4, N'2024-03-18', NULL, N'Pendente');
INSERT INTO Ordens (ClienteID, TecnicoID, DataAbertura, DataConclusao, Status) VALUES (30, 5, N'2024-04-04', NULL, N'Agendada');

INSERT INTO Servicos (OrdemID, ProdutoID, Descricao) VALUES (1, 3, N'Serviço realizado com Produto 3');
INSERT INTO Servicos (OrdemID, ProdutoID, Descricao) VALUES (1, 1, N'Serviço realizado com Produto 1');
INSERT INTO Servicos (OrdemID, ProdutoID, Descricao) VALUES (1, 3, N'Serviço realizado com Produto 3');
INSERT INTO Servicos (OrdemID, ProdutoID, Descricao) VALUES (2, 4, N'Serviço realizado com Produto 4');
INSERT INTO Servicos (OrdemID, ProdutoID, Descricao) VALUES (2, 1, N'Serviço realizado com Produto 1');
INSERT INTO Servicos (OrdemID, ProdutoID, Descricao) VALUES (3, 4, N'Serviço realizado com Produto 4');
INSERT INTO Servicos (OrdemID, ProdutoID, Descricao) VALUES (3, 5, N'Serviço realizado com Produto 5');
INSERT INTO Servicos (OrdemID, ProdutoID, Descricao) VALUES (3, 4, N'Serviço realizado com Produto 4');
INSERT INTO Servicos (OrdemID, ProdutoID, Descricao) VALUES (4, 4, N'Serviço realizado com Produto 4');
INSERT INTO Servicos (OrdemID, ProdutoID, Descricao) VALUES (5, 5, N'Serviço realizado com Produto 5');
INSERT INTO Servicos (OrdemID, ProdutoID, Descricao) VALUES (5, 5, N'Serviço realizado com Produto 5');
INSERT INTO Servicos (OrdemID, ProdutoID, Descricao) VALUES (6, 2, N'Serviço realizado com Produto 2');
INSERT INTO Servicos (OrdemID, ProdutoID, Descricao) VALUES (7, 5, N'Serviço realizado com Produto 5');
INSERT INTO Servicos (OrdemID, ProdutoID, Descricao) VALUES (8, 4, N'Serviço realizado com Produto 4');
INSERT INTO Servicos (OrdemID, ProdutoID, Descricao) VALUES (8, 2, N'Serviço realizado com Produto 2');
INSERT INTO Servicos (OrdemID, ProdutoID, Descricao) VALUES (9, 4, N'Serviço realizado com Produto 4');
INSERT INTO Servicos (OrdemID, ProdutoID, Descricao) VALUES (10, 4, N'Serviço realizado com Produto 4');
INSERT INTO Servicos (OrdemID, ProdutoID, Descricao) VALUES (10, 5, N'Serviço realizado com Produto 5');
INSERT INTO Servicos (OrdemID, ProdutoID, Descricao) VALUES (11, 5, N'Serviço realizado com Produto 5');
INSERT INTO Servicos (OrdemID, ProdutoID, Descricao) VALUES (12, 4, N'Serviço realizado com Produto 4');
INSERT INTO Servicos (OrdemID, ProdutoID, Descricao) VALUES (12, 2, N'Serviço realizado com Produto 2');
INSERT INTO Servicos (OrdemID, ProdutoID, Descricao) VALUES (13, 4, N'Serviço realizado com Produto 4');
INSERT INTO Servicos (OrdemID, ProdutoID, Descricao) VALUES (14, 4, N'Serviço realizado com Produto 4');
INSERT INTO Servicos (OrdemID, ProdutoID, Descricao) VALUES (15, 4, N'Serviço realizado com Produto 4');
INSERT INTO Servicos (OrdemID, ProdutoID, Descricao) VALUES (16, 4, N'Serviço realizado com Produto 4');
INSERT INTO Servicos (OrdemID, ProdutoID, Descricao) VALUES (16, 2, N'Serviço realizado com Produto 2');
INSERT INTO Servicos (OrdemID, ProdutoID, Descricao) VALUES (17, 1, N'Serviço realizado com Produto 1');
INSERT INTO Servicos (OrdemID, ProdutoID, Descricao) VALUES (17, 4, N'Serviço realizado com Produto 4');
INSERT INTO Servicos (OrdemID, ProdutoID, Descricao) VALUES (17, 1, N'Serviço realizado com Produto 1');
INSERT INTO Servicos (OrdemID, ProdutoID, Descricao) VALUES (18, 4, N'Serviço realizado com Produto 4');
INSERT INTO Servicos (OrdemID, ProdutoID, Descricao) VALUES (19, 1, N'Serviço realizado com Produto 1');
INSERT INTO Servicos (OrdemID, ProdutoID, Descricao) VALUES (19, 2, N'Serviço realizado com Produto 2');
INSERT INTO Servicos (OrdemID, ProdutoID, Descricao) VALUES (19, 5, N'Serviço realizado com Produto 5');
INSERT INTO Servicos (OrdemID, ProdutoID, Descricao) VALUES (20, 5, N'Serviço realizado com Produto 5');
INSERT INTO Servicos (OrdemID, ProdutoID, Descricao) VALUES (20, 5, N'Serviço realizado com Produto 5');
INSERT INTO Servicos (OrdemID, ProdutoID, Descricao) VALUES (20, 2, N'Serviço realizado com Produto 2');
INSERT INTO Servicos (OrdemID, ProdutoID, Descricao) VALUES (21, 6, N'Serviço realizado com Produto 6');
INSERT INTO Servicos (OrdemID, ProdutoID, Descricao) VALUES (21, 9, N'Serviço realizado com Produto 9');
INSERT INTO Servicos (OrdemID, ProdutoID, Descricao) VALUES (22, 7, N'Serviço realizado com Produto 7');
INSERT INTO Servicos (OrdemID, ProdutoID, Descricao) VALUES (23, 8, N'Serviço realizado com Produto 8');
INSERT INTO Servicos (OrdemID, ProdutoID, Descricao) VALUES (23, 10, N'Serviço realizado com Produto 10');
INSERT INTO Servicos (OrdemID, ProdutoID, Descricao) VALUES (24, 6, N'Serviço realizado com Produto 6');
INSERT INTO Servicos (OrdemID, ProdutoID, Descricao) VALUES (25, 7, N'Serviço realizado com Produto 7');
INSERT INTO Servicos (OrdemID, ProdutoID, Descricao) VALUES (26, 8, N'Serviço realizado com Produto 8');
INSERT INTO Servicos (OrdemID, ProdutoID, Descricao) VALUES (27, 9, N'Serviço realizado com Produto 9');
INSERT INTO Servicos (OrdemID, ProdutoID, Descricao) VALUES (28, 10, N'Serviço realizado com Produto 10');
